### ISSUE TITLE
Add an RSS and/or Atom feed

### ISSUE THREAD

**Issue by polyzen** [arp242/vimlog#3]
Unless there's another way to be notified of additions to VimLog, a feed would be much appreciated.

**Comment by arp242** [comment]
Yeah, I actually did some work on this a while ago; but interest in this was lacklustre enough that I didn't really follow through with it.

**Comment by arp242** [comment]
GitHub as an Atom feed for commits: https://github.com/arp242/vimlog/commits/master.atom, and you can also watch the GitHub repo.

This seems sufficient for the time being. The traffic for this page is very low, and unless it picks up I don't want to spend too much time on it.

**Comment by polyzen** [comment]
Didn't realize it all went through this repo. That's sufficient for me, thank you.

**Comment by yjfguhd** [comment]
FWIW, I'd find this useful.

**Comment by arp242** [comment]
The commit feed should be sufficient, no?

**Comment by yjfguhd** [comment]
Sorry, I was under the impression this issue was for following just the curated list of Vim changes, on https://www.arp242.net/vimlog/, as opposed to following all commits for the web site itself.

**Comment by tammersaleh** [comment]
I'd love to see an actual RSS feed.  Can subscribe to the github RSS feed, but it only seems to give the commit messages, which means I have to click through to see what the vim changes actually are.

**Comment by arp242** [comment]
I'll happily review & accept any patches @tammersaleh; basically you just need to modify the `gen.py` script to also write a RSS file. Start by [moving this](https://github.com/arp242/vimlog/blob/master/gen.py#L515) to a `gen_html()` function or some such, and then add a `gen_rss()` function which more or less does the same, except create a RSS file instead of a HTML file. Some other things may need to be abstracted a bit as well, as it's just a quick script I wrote.
